version: "3.7"
services:
  expfrontend:
    image: ${DOCKER_URL}
    environment:
      SPADE_VERSION: ${SPADE_VERSION}
  chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
    logging:
      driver: "none"
  firefox:
    image: selenium/standalone-firefox
    volumes:
      - /dev/shm:/dev/shm
    logging:
      driver: "none"
  browserstack:
    build: ./e2e
    environment:
      BS_ACCOUNT: ${BS_ACCOUNT}
      BS_KEY: ${BS_KEY}
      BS_ENV: docker
      USE_LOCAL_BROWSER: ${USE_LOCAL_BROWSER}
      SPADE_VERSION: ${SPADE_VERSION}
    depends_on:
      - expfrontend
