version: "3.7"
services:
  expfrontend:
    image: ${DOCKER_URL}
    environment:
      SPADE_VERSION: ${SPADE_VERSION}
    ports:
      - "4000:4000"
  browserstack:
    build: ./e2e
    environment:
      BS_ACCOUNT: ${BS_ACCOUNT}
      BS_KEY: ${BS_KEY}
      BS_ENV: docker
    depends_on:
      - expfrontend
