version: "3.7"
services:
  expfrontend:
    image: ${DOCKER_URL}
    ports:
      - "4000:4000"
  puppet:
    build: ./smoke-test
    environment:
      URL: http://expfrontend:4000/
    depends_on:
      - expfrontend
