apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/kube-default: true
    app: jenkins
    component: agent
spec:
  containers:
    - name: jnlp
      image: jenkinsci/jnlp-slave
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
      imagePullPolicy: Always
    - name: dind
      image: docker:18.05-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
    - name: node
      image: node:10.15.3-alpine
      command:
        - sh
      tty: true
    - name: practiv-maven
        command:
          - cat
        image: docker.ci.shift21.ffx.nz/io.practiv/build/practiv-build-maven-seeded:3.2
        imagePullPolicy: IfNotPresent
        env:
          - name: DOCKER_HOST
            value: tcp://localhost:2375
        securityContext:
          runAsUser: 10000
          fsGroup: 10000
        tty: true
  volumes:
    - name: dind-storage
      emptyDir: {}
