export enum ContentBlockType {
  GrayDefconArticleUnit = "GrayDefconArticleUnit",
  DefconArticleUnit = "DefconArticleUnit",
  BasicArticleUnit = "BasicArticleUnit",
  BigImageArticleUnit = "BigImageArticleUnit",
  HalfWidthImageArticleUnit = "HalfWidthImageArticleUnit",
  BasicArticleTitleUnit = "BasicArticleTitleUnit",
  ImageLinkUnit = "ImageLinkUnit",
  BasicAdUnit = "BasicAdUnit",
  ErrorBlock = "ErrorBlock",
  Container = "Container",
  ColumnContainer = "ColumnContainer",
  Footer = "Footer",
  BasicArticleSection = "BasicArticleSection",
  ExpandableArticleSection = "ExpandableArticleSection",
  Header = "Header",
  BreakingNews = "BreakingNews",
  ExternalContentUnit = "ExternalContentUnit",
  WeatherUnit = "WeatherUnit",
  ExperimentContainer = "ExperimentContainer",
  FeatureContainer = "FeatureContainer",
  Recommendations = "Recommendations",
  GridContainer = "GridContainer",
  ResponsiveBigImageArticle = "ResponsiveBigImageArticle",
  ModuleTitle = "ModuleTitle",
  DarkGradientArticle = "DarkGradientArticle"
}
