export enum Section {
  Latest = '',
  Sport = 'sport',
  National = 'national',
  World = 'world',
  Business = 'business',
  Opinion = 'opinion',
  Technology = 'technology',
  Homed = 'life-style/homed',
  LifeStyle = 'life-style',
  Entertainment = 'entertainment',
  Travel = 'travel',
  Motoring = 'motoring',
  StuffNation = 'stuff-nation',
  ClimateChange = 'environment/climate-news',
  WellGood = 'life-style/well-good',
  Premium = 'national/premium',
  GoodReads = 'good-reads',
  Noted = 'national/noted',
  NowToLove = 'life-style/now-to-love',
  HomesToLove = 'life-style/homes-to-love',
  FoodToLove = 'life-style/food-to-love',
  BeautyHeaven = 'life-style/beauty-heaven',
  Metro = 'life-style/metro',
  Newsroom = 'national/newsroom',
  SponsoredContent = 'sponsored-content',
  Tarana = 'tarana'
}
