version: "3.7"
services:
  lastestspade:
    image: gcr.io/shared-218200/nz.stuff/experience/experience-frontend:1.519
    environment:
      - SPADE_ENV=production
      - SPADE_VERSION=1.519
  oldspade:
    image: ${DOCKER_IMAGE}
    environment:
      - SPADE_ENV=production
      - SPADE_VERSION=${VERSION}
  nginx-proxy:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
