version: "3.7"
services:
  oldspade:
    image: gcr.io/shared-218200/nz.stuff/experience/experience-frontend:1.600
    environment:
      SPADE_ENV: production
      SPADE_VERSION: 1.600
  newspade:
    image: stuff-experience-frontend:latest
    environment:
      SPADE_ENV: production
      SPADE_VERSION: 1.100
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
