export enum HandlerInputType {
  TopStoriesArticleList = "TopStoriesArticleList",
  ArticleList = "ArticleList",
  Banner = "Banner",
  MoreSectionExperimentHandlerInput = "MoreSectionExperiment",
  ExpandableArticleSection = "ExpandableArticleSection",
  ExpandableArticleList = "ExpandableArticleList",
  ArticleSection = "ArticleSection",
  BreakingNews = "BreakingNews",
  MidStrip = "MidStrip",
  MiniMidStrip = "MiniMidStrip",
  ExternalContent = "ExternalContent",
  Page = "Page",
  Weather = "Weather",
  Experiment = "Experiment",
  Feature = "Feature",
  Recommendations = "Recommendations",
  NewsSix = "NewsSix",
  NewsSixGrid = "NewsSixGrid",
  SixImage = "SixImage",
  SixImageGrid = "SixImageGrid",
  LargeLeadSix = "LargeLeadSix",
  LargeLeadSixGrid = "LargeLeadSixGrid",
  ListGrid = "ListGrid",
  ColumnGrid = "ColumnGrid"
}
