export enum HandlerInputType {
  TopStoriesExperiment = "TopStoriesExperiment",
  TopStoriesArticleList = "TopStoriesArticleList",
  TopStoriesArticleListGroupOne = "TopStoriesArticleListGroupOne",
  TopStoriesArticleListGroupTwo = "TopStoriesArticleListGroupTwo",
  ArticleList = "ArticleList",
  Banner = "Banner",
  MoreSectionExperimentHandlerInput = "MoreSectionExperiment",
  ExpandableArticleSection = "ExpandableArticleSection",
  ExpandableArticleList = "ExpandableArticleList",
  ArticleSection = "ArticleSection",
  BreakingNews = "BreakingNews",
  MidStrip = "MidStrip",
  MiniMidStrip = "MiniMidStrip",
  ExternalContent = "ExternalContent",
  Page = "Page",
  Weather = "Weather",
  Experiment = "Experiment",
  Feature = "Feature",
  Recommendations = "Recommendations",
  NewsSix = "NewsSix"
}
