export enum AnalyticsEventsType {
  FOOTER_MENU,
  WEATHER_BAR_OPENED,
  WEATHER_BAR_CLOSED,
  WEATHER_EXIT_BUTTON,
  WEATHER_LOCATION_CHANGED,
  STUFF_LOGO,
  MENU_NAV_OPEN,
  MENU_NAV_CLOSE,
  BREAKING_NEWS_OPEN,
  BREAKING_NEWS_CLOSE
}
