export enum AnalyticsEventsType {
  MENU_NAV_SECTION_CLICKED,
  MORE_BUTTON_CLICKED,
  FOOTER_MENU,
  WEATHER_BAR_OPENED,
  WEATHER_BAR_CLOSED,
  WEATHER_EXIT_BUTTON,
  WEATHER_LOCATION_CHANGED,
  STUFF_LOGO_CLICKED,
  MENU_NAV_OPENED,
  MENU_NAV_CLOSED,
  BREAKING_NEWS_OPEN,
  BREAKING_NEWS_CLOSE
}
