export enum AnalyticsEventsType {
  PAGE_LOAD,
  LOGIN_CLIKED,
  AVATAR_CLICKED,
  MENU_NAV_SECTION_CLICKED,
  MORE_BUTTON_CLICKED,
  FOOTER_MENU_CLICKED,
  WEATHER_LOCATION_CHANGED,
  STUFF_LOGO_CLICKED,
  MENU_NAV_OPENED,
  BREAKING_NEWS_OPENED,
  BREAKING_NEWS_CLOSED,
  HOMEPAGE_STRAP_CLICKED,
  EXPERIMENT
}
